[project]
name = "users"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "asyncpg>=0.30.0",
    "dishka>=1.4.2",
    "fastapi>=0.115.6",
    "pre-commit>=4.0.1",
    "sqlalchemy>=2.0.36",
]
